---
- name: install tftp-server
  dnf:
    name: 
      - tftp-server
      - syslinux-tftpboot
    state: present

- name: start tftp-server
  systemd:
    name: tftp.service
    enabled: true
    state: started

- name: create dir for pxe configsyslinux-tftpboot
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    owner: root
    group: root
    mode: '751'

- name: template pxe default config
  template:
    src: templates/default
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    owner: root
    group: root
    mode: '0644'

- name: copy file for pxe
  copy:
    src: "/tftpboot/{{ item }}"
    dest: /var/lib/tftpboot/
    remote_src: true  
  with_items: 
    - ldlinux.c32
    - libutil.c32
    - menu.c32
    - pxelinux.0
    - vesamenu.c32
    
  